#!/usr/bin/env python3
"""
fill_paper.py
=============
Re-runs the demo pipeline and generates:
  1. results/tables/table3_nss_params.tex
  2. results/tables/table4_horse_race.tex
  3. results/tables/table5_panel_reg.tex
  4. results/figures/fig4_robustness_delta.pdf  (copy of fig5)
  5. Prints all PLACEHOLDER values for pasting into the LaTeX paper

Run from the paper2a_kappa_yield_curve/ directory:
  cd papers/paper2/paper2a_kappa_yield_curve
  python fill_paper.py
"""

import os
import sys
import warnings
import shutil
import numpy as np
import pandas as pd
from scipy.optimize import minimize, differential_evolution
from scipy.stats import chi2

warnings.filterwarnings("ignore")

# ── Add parent dir so we can import kappa_pipeline ────────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
from kappa_pipeline import (
    generate_demo_data, extract_kappa, fit_nss_panel, fit_cir,
    horse_race, panel_regression, nss_curve,
    COUNTRY_LABELS, DELTA_DEFAULT_SOVEREIGN, DELTA_DEFAULT_CORPORATE,
)

TAB_DIR = "results/tables"
FIG_DIR = "results/figures"
os.makedirs(TAB_DIR, exist_ok=True)
os.makedirs(FIG_DIR, exist_ok=True)

# ── 1. Re-generate demo data and run pipeline ──────────────────────────────────
print("=== Loading real data ===")
df_raw = pd.read_csv("data/sukuk_panel.csv", parse_dates=["obs_date"])
df = extract_kappa(df_raw)

print("\n=== Fitting NSS panel ===")
nss_df = pd.read_csv("results/nss_params.csv", parse_dates=["obs_date"])

print("\n=== Running horse race ===")
hr = pd.read_csv("results/horse_race.csv")

print("\n=== Running CIR GMM ===")
cir_results = {}
for country, grp in df.groupby("country"):
    ts = grp.groupby("obs_date")["kappa_hat"].mean().sort_index().values
    cir_results[country] = fit_cir(ts)

print("\n=== Running panel regression ===")
models = panel_regression(df)

# ──────────────────────────────────────────────────────────────────────────────
# TABLE 3: NSS parameters (mean per country over all dates)
# ──────────────────────────────────────────────────────────────────────────────
def export_table3_nss(nss_df, path):
    country_map = {"SA": "Saudi Arabia", "AE": "UAE", "QA": "Qatar",
                   "MY": "Malaysia", "ID": "Indonesia"}
    country_order = ["SA", "AE", "QA", "MY", "ID"]

    rows = []
    for code in country_order:
        c_df = nss_df[nss_df["country"] == code]
        if len(c_df) == 0:
            continue
        label = country_map.get(code, code)
        b0 = c_df["beta0"].mean()
        b1 = c_df["beta1"].mean()
        b2 = c_df["beta2"].mean()
        b3 = c_df["beta3"].mean()
        t1 = c_df["tau1"].mean()
        t2 = c_df["tau2"].mean()
        rmse = c_df["nss_rmse_bps"].mean()
        rows.append((label, b0, b1, b2, b3, t1, t2, rmse))

    # Pooled GCC (SA, AE, QA) and SEA (MY, ID)
    gcc = nss_df[nss_df["country"].isin(["SA", "AE", "QA"])]
    sea = nss_df[nss_df["country"].isin(["MY", "ID"])]
    for label, grp in [("Pooled GCC", gcc), ("Pooled SEA", sea)]:
        if len(grp) == 0:
            continue
        rows.append((label, grp["beta0"].mean(), grp["beta1"].mean(),
                     grp["beta2"].mean(), grp["beta3"].mean(),
                     grp["tau1"].mean(), grp["tau2"].mean(),
                     grp["nss_rmse_bps"].mean()))

    with open(path, "w") as f:
        f.write("% Table 3: NSS Parameter Estimates (mean over 2014-2025 panel)\n")
        f.write("% Auto-generated by fill_paper.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Nelson--Siegel--Svensson Parameter Estimates (Period Average).}\n")
        f.write("\\label{tab:nss_params_auto}\n")
        f.write("\\small\n")
        f.write("\\resizebox{\\textwidth}{!}{%\n")
        f.write("\\begin{tabular}{lcccccc|c}\n\\toprule\n")
        f.write("\\textbf{Country/Group} & $\\hat{\\beta}_0$ & $\\hat{\\beta}_1$ "
                "& $\\hat{\\beta}_2$ & $\\hat{\\beta}_3$ & $\\hat{\\tau}_1$ "
                "& $\\hat{\\tau}_2$ & \\textbf{RMSE} \\\\\n")
        f.write("& \\textit{(level)} & \\textit{(slope)} & \\textit{(curv.~1)} "
                "& \\textit{(curv.~2)} & & & \\textit{(bps)} \\\\\n")
        f.write("\\midrule\n")
        for i, (lbl, b0, b1, b2, b3, t1, t2, rmse) in enumerate(rows):
            if lbl.startswith("Pooled") and i > 0:
                f.write("\\midrule\n")
            f.write(f"{lbl} & {b0*100:.3f}\\% & {b1*100:.3f}\\% "
                    f"& {b2*100:.3f}\\% & {b3*100:.3f}\\% "
                    f"& {t1:.2f} & {t2:.2f} & {rmse:.2f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n}\n")
        f.write("\\caption*{\\textit{Note:} Parameters estimated by NLS over "
                "2014--2025 panel, averaged over quarterly observations. "
                "$\\hat{\\beta}_0$ = long-run $\\kappa$ level (\\%). "
                "RMSE in basis points.}\n")
        f.write("\\end{table}\n")
    print(f"[export] Saved {path}")
    return rows

nss_rows = export_table3_nss(nss_df, f"{TAB_DIR}/table3_nss_params.tex")

# ──────────────────────────────────────────────────────────────────────────────
# TABLE 4: Horse race
# ──────────────────────────────────────────────────────────────────────────────
def export_table4_horse_race(hr, path):
    with open(path, "w") as f:
        f.write("% Table 4: Horse Race — κ-model vs SOFR-model vs Random Walk\n")
        f.write("% Auto-generated by fill_paper.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Out-of-Sample Forecast Accuracy: $\\kappa$-Model vs.\\ Alternatives}\n")
        f.write("\\label{tab:horse_race_auto}\n")
        f.write("\\small\n")
        f.write("\\resizebox{\\textwidth}{!}{%\n")
        f.write("\\begin{tabular}{lcccccc}\n\\toprule\n")
        f.write("\\textbf{Model} & \\textbf{RMSE (bps)} & \\textbf{MAE (bps)} "
                "& $\\mathbf{R^2}$ & \\textbf{DM stat} & \\textbf{DM $p$-val} \\\\\n")
        f.write("\\midrule\n")
        for _, row in hr.iterrows():
            model = row["Model"]
            rmse = f"{row['RMSE_bps']:.2f}" if row['RMSE_bps'] > 0.01 else "$<$0.01"
            mae  = f"{row['MAE_bps']:.2f}" if row['MAE_bps'] > 0.01 else "$<$0.01"
            r2   = f"{row['R2']:.3f}" if not np.isnan(row['R2']) else "---"
            dm   = f"{row['DM_vs_SOFR']:.2f}" if not np.isnan(row['DM_vs_SOFR']) else "---"
            pval = "0.000" if (not np.isnan(row['DM_pval']) and row['DM_pval'] < 0.001) \
                   else (f"{row['DM_pval']:.3f}" if not np.isnan(row['DM_pval']) else "---")
            f.write(f"$\\kappa$-model & {rmse} & {mae} & {r2} & {dm} & {pval} \\\\\n"
                    if model == "κ-model" else
                    f"{model} & {rmse} & {mae} & {r2} & {dm} & {pval} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n}\n")
        f.write("\\caption*{\\textit{Note:} $\\kappa$-model: predicted spread "
                "$= \\hat{\\kappa}(1-\\delta)$. SOFR-model: OLS regression of "
                "spread on SOFR, maturity, rating, country FE. DM test: $H_0$ "
                "equal predictive accuracy; negative stat $\\Rightarrow$ "
                "$\\kappa$-model is more accurate. $p < 0.001$ indicates rejection at "
                "all conventional levels.}\n")
        f.write("\\end{table}\n")
    print(f"[export] Saved {path}")

export_table4_horse_race(hr, f"{TAB_DIR}/table4_horse_race.tex")

# ──────────────────────────────────────────────────────────────────────────────
# TABLE 5: Panel regression
# ──────────────────────────────────────────────────────────────────────────────
def export_table5_panel(models, df, path):
    """Extract coefficients and format panel regression table."""
    if not models:
        print("[panel_reg] No models — statsmodels missing. Generating synthetic results.")
        # Generate plausible synthetic table (demo data, κ by construction = spread/(1-δ)*10000)
        with open(path, "w") as f:
            f.write("% Table 5: Panel Regression (synthetic demo — awaiting Bloomberg data)\n")
            f.write("% Auto-generated by fill_paper.py\n")
            f.write("% NOTE: Exact results require real data; see horse_race.csv\n")
        return {}

    n_obs = len(df.dropna(subset=["kappa_hat", "spread_bps"]))
    specs = list(models.keys())

    with open(path, "w") as f:
        f.write("% Table 5: Panel Regression Results\n")
        f.write("% Auto-generated by fill_paper.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Panel Regression: Sukuk Spread on $\\hat{\\kappa}$}\n")
        f.write("\\label{tab:panel_auto}\n")
        f.write("\\small\n")
        f.write("\\resizebox{\\textwidth}{!}{%\n")

        ncol = len(specs)
        col_fmt = "l" + "c" * ncol
        f.write(f"\\begin{{tabular}}{{{col_fmt}}}\n\\toprule\n")

        # Header
        header = " & " + " & ".join([f"({i+1})" for i in range(ncol)]) + " \\\\\n"
        f.write(header)
        names_row = " & " + " & ".join([s.split(")")[0].strip("(").strip() for s in specs]) + " \\\\\n"
        f.write(names_row)
        f.write("\\midrule\n")

        # β(κ̂) row
        betas = []
        ses = []
        pvals_h1 = []  # p-value for H0: β=1
        r2s = []
        for name, m in models.items():
            beta = m.params.get("kappa_hat", np.nan)
            se   = m.bse.get("kappa_hat", np.nan)
            betas.append(beta)
            ses.append(se)
            # t-stat for H0: β=1
            t_h1 = (beta - 1) / se if se > 0 else np.nan
            from scipy.stats import norm
            pval_h1 = 2 * (1 - norm.cdf(abs(t_h1))) if not np.isnan(t_h1) else np.nan
            pvals_h1.append(pval_h1)
            r2s.append(m.rsquared)

        def sig_stars(p):
            if np.isnan(p): return ""
            if p < 0.01: return "***"
            if p < 0.05: return "**"
            if p < 0.10: return "*"
            return ""

        beta_str = "$\\hat{\\kappa}$ ($\\hat{\\beta}$) & " + \
                   " & ".join([f"{b:.4f}{sig_stars(m.pvalues.get('kappa_hat',1))}"
                                for b, m in zip(betas, models.values())]) + " \\\\\n"
        se_str = " & " + " & ".join([f"({s:.4f})" for s in ses]) + " \\\\\n"
        pval_str = "$H_0$: $\\beta=1$, $p$ & " + \
                   " & ".join([(f"{p:.3f}" if not np.isnan(p) else "---") for p in pvals_h1]) + " \\\\[4pt]\n"

        f.write(beta_str)
        f.write(se_str)
        f.write(pval_str)

        # Full spec controls if available (spec 5)
        full_name = "(5) Full" if "(5) Full" in models else None
        for ctrl_var, ctrl_label in [("rating_code", "Rating"), ("log_maturity", "$\\log$(Maturity)")]:
            if full_name and ctrl_var in models[full_name].params:
                coef = models[full_name].params[ctrl_var]
                se_c = models[full_name].bse[ctrl_var]
                p_c  = models[full_name].pvalues[ctrl_var]
                f.write(f"{ctrl_label} & & & & & {coef:.4f}{sig_stars(p_c)} \\\\\n")
                f.write(f" & & & & & ({se_c:.4f}) \\\\\n")

        f.write("\\midrule\n")
        fe_rows = {
            "(1) OLS":       ("No",  "No"),
            "(2) Country FE":("Yes", "No"),
            "(3) Sector FE": ("No",  "Yes"),
            "(4) Two-way FE":("Yes", "Yes"),
        }
        cfe = [fe_rows.get(s, ("Yes", "Yes"))[0] for s in specs]
        sfe = [fe_rows.get(s, ("Yes", "Yes"))[1] for s in specs]
        f.write("Country FE & " + " & ".join(cfe) + " \\\\\n")
        f.write("Sector FE  & " + " & ".join(sfe) + " \\\\\n")
        f.write(f"$N$ obs & \\multicolumn{{{ncol}}}{{c}}{{{n_obs:,}}} \\\\\n")
        r2_str = "$R^2$ & " + " & ".join([f"{r:.3f}" for r in r2s]) + " \\\\\n"
        f.write(r2_str)

        f.write("\\bottomrule\n\\end{tabular}\n}\n")
        f.write("\\caption*{\\textit{Note:} Dependent variable: sukuk spread (bps). "
                "HC3 heteroskedasticity-robust standard errors in parentheses. "
                "*, **, *** indicate significance at 10\\%, 5\\%, 1\\% levels. "
                "$H_0$: $\\beta=1$ (ABIslam2026 Theorem~1).}\n")
        f.write("\\end{table}\n")

    print(f"[export] Saved {path}")
    return {"betas": betas, "ses": ses, "pvals_h1": pvals_h1, "r2s": r2s, "n_obs": n_obs}

panel_stats = export_table5_panel(models, df, f"{TAB_DIR}/table5_panel_reg.tex")

# ──────────────────────────────────────────────────────────────────────────────
# Figure 4: copy fig5_robustness_delta.pdf → fig4_robustness_delta.pdf
# ──────────────────────────────────────────────────────────────────────────────
src = f"{FIG_DIR}/fig5_robustness_delta.pdf"
dst = f"{FIG_DIR}/fig4_robustness_delta.pdf"
if os.path.exists(src):
    shutil.copy2(src, dst)
    print(f"[figures] Copied {src} → {dst}")

# ──────────────────────────────────────────────────────────────────────────────
# PRINT ALL PLACEHOLDER VALUES
# ──────────────────────────────────────────────────────────────────────────────
print("\n" + "="*70)
print("PLACEHOLDER VALUES FOR PAPER")
print("="*70)

# Counts
N_total = len(df)
N_issuers = df["sukuk_id"].nunique()
N_countries = df["country"].nunique()
N_obs = N_total
print(f"\n--- Panel size ---")
print(f"N_total observations : {N_total}")
print(f"N unique sukuk/issuers: {N_issuers}")
print(f"N countries           : {N_countries}")
print(f"T_periods (quarters)  : {df['obs_date'].nunique()}")
print(f"Date range            : {df['obs_date'].min().strftime('%Y-%m')} – {df['obs_date'].max().strftime('%Y-%m')}")

# κ̂ range
kappa_min = df["kappa_pct"].min()
kappa_max = df["kappa_pct"].max()
kappa_mean = df["kappa_pct"].mean()
print(f"\n--- κ̂ statistics ---")
print(f"Overall mean κ̂       : {kappa_mean:.2f}% p.a.")
print(f"κ̂ range               : {kappa_min:.2f}% – {kappa_max:.2f}% p.a.")

# Per-country means
print(f"\n--- Per-country mean κ̂ ---")
for country, grp in df.groupby("country"):
    lbl = COUNTRY_LABELS.get(country, country)
    print(f"  {lbl:15s}: {grp['kappa_pct'].mean():.2f}% (min {grp['kappa_pct'].min():.2f}%, max {grp['kappa_pct'].max():.2f}%)")

# GCC vs SEA
gcc_mean = df[df["country"].isin(["SA","AE","QA"])]["kappa_pct"].mean()
sea_mean = df[df["country"].isin(["MY","ID"])]["kappa_pct"].mean()
print(f"\n--- GCC vs SEA ---")
print(f"GCC mean κ̂  : {gcc_mean:.2f}% p.a.")
print(f"SEA mean κ̂  : {sea_mean:.2f}% p.a.")
print(f"GCC – SEA   : {gcc_mean - sea_mean:+.2f} pp")

# NSS params summary
print(f"\n--- NSS params (mean over all country-date cells) ---")
for code in ["SA", "AE", "QA", "MY", "ID"]:
    c = nss_df[nss_df["country"] == code]
    if len(c) == 0: continue
    lbl = {"SA":"Saudi Arabia","AE":"UAE","QA":"Qatar","MY":"Malaysia","ID":"Indonesia"}[code]
    print(f"  {lbl:15s}: β₀={c['beta0'].mean()*100:.3f}% β₁={c['beta1'].mean()*100:.3f}% "
          f"β₂={c['beta2'].mean()*100:.3f}% β₃={c['beta3'].mean()*100:.3f}% "
          f"τ₁={c['tau1'].mean():.2f} τ₂={c['tau2'].mean():.2f} RMSE={c['nss_rmse_bps'].mean():.2f}bps")

# Horse race
print(f"\n--- Horse race ---")
for _, row in hr.iterrows():
    model = row["Model"]
    rmse = row["RMSE_bps"]
    mae  = row["MAE_bps"]
    r2   = row["R2"]
    dm   = row["DM_vs_SOFR"]
    pval = row["DM_pval"]
    rmse_str = "<0.01" if rmse < 0.01 else f"{rmse:.2f}"
    mae_str  = "<0.01" if mae < 0.01 else f"{mae:.2f}"
    dm_str   = f"{dm:.2f}" if not np.isnan(dm) else "n/a"
    pval_str = f"{pval:.4f}" if not np.isnan(pval) else "n/a"
    print(f"  {model:15s}: RMSE={rmse_str}bps MAE={mae_str}bps R²={r2:.3f} DM={dm_str} p={pval_str}")

# CIR results
print(f"\n--- CIR GMM results ---")
feller_count = 0
for country, res in cir_results.items():
    if "error" in res: continue
    lbl = COUNTRY_LABELS.get(country, country)
    hl = res["half_life_months"]
    feller = res["feller_ok"]
    if feller: feller_count += 1
    hl_str = f"{hl:.1f}" if np.isfinite(hl) else "∞"
    print(f"  {lbl:15s}: α={res['alpha']:.3f} κ̄={res['kbar']*100:.2f}% "
          f"ν={res['nu']:.3f} half-life={hl_str}mo Feller={'✓' if feller else '✗'} "
          f"J={res['j_stat']:.2f}")
print(f"  Feller satisfied: {feller_count}/{len(cir_results)} countries")

# Panel regression summary
if panel_stats:
    print(f"\n--- Panel regression ---")
    print(f"N obs: {panel_stats['n_obs']:,}")
    for i, (b, s, p) in enumerate(zip(panel_stats['betas'],
                                       panel_stats['ses'],
                                       panel_stats['pvals_h1']), 1):
        print(f"  Spec ({i}): β={b:.4f} SE={s:.4f} p(H₀:β=1)={p:.4f}")
    print(f"  R² range: {min(panel_stats['r2s']):.3f} – {max(panel_stats['r2s']):.3f}")

print("\n" + "="*70)
print("ACTION REQUIRED: Edit paper2a_kappa_yield_curve.tex")
print("  1. Replace all \\PLACEHOLDER{} with values above")
print("  2. Replace Figure fbox placeholders with \\includegraphics commands")
print("  3. Use table files in results/tables/")
print("="*70)
