#!/usr/bin/env python3
"""
icds_pipeline.py — Analysis pipeline for Paper 2C.

Generates all tables (LaTeX) and figures (PDF):
  Table 1: Descriptive statistics — κ̂, s_obs, s*, s_conv by country
  Table 2: Pricing comparison — annual s*(ι=0) vs s_conv(ι=SOFR) vs Damodaran CDS
  Table 3: Long-run pricing — κ̄(1−δ) vs 2025 CDS; riba premium quantification
  Table 4: Gas cost benchmarks — iCDS lifecycle on Arbitrum
  Table 5: Welfare analysis — certainty-equivalent wealth, 3 strategies × 3 γ
  Table 6: Jurisdictional analysis — VARA/BNM/MAS/CFTC/FCA summary

  Fig 1:  s*(ι=0) vs s_conv(ι=SOFR) vs Damodaran CDS — 7-panel time series
  Fig 2:  Scatter: s_conv vs Damodaran CDS (all 1,176 obs)
  Fig 3:  Riba premium bps by country × year (stacked bar)
  Fig 4:  Gas cost comparison — Arbitrum vs Ethereum (horizontal bar)
  Fig 5:  Welfare analysis — certainty-equivalent wealth for 3 strategies
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from pathlib import Path

HERE    = Path(__file__).parent
DATA    = HERE / "data"
RES     = HERE / "results"
TABS    = RES / "tables"
FIGS    = RES / "figures"
for d in [TABS, FIGS]:
    d.mkdir(parents=True, exist_ok=True)

DELTA = 0.60
LGD   = 1 - DELTA

CIR = {
    "UAE":          dict(kbar=0.01630, alpha=0.803, nu=0.046),
    "Bahrain":      dict(kbar=0.08096, alpha=0.668, nu=0.069),
    "Indonesia":    dict(kbar=0.04072, alpha=0.632, nu=0.055),
    "Kuwait":       dict(kbar=0.01686, alpha=0.925, nu=0.049),
    "Malaysia":     dict(kbar=0.02453, alpha=0.762, nu=0.043),
    "Qatar":        dict(kbar=0.01981, alpha=0.684, nu=0.050),
    "Saudi Arabia": dict(kbar=0.02409, alpha=0.718, nu=0.065),
}

# ── Load data ───────────────────────────────────────────────────────────────
def load():
    panel   = pd.read_csv(DATA / "icds_panel.csv",   parse_dates=["obs_date"])
    cir_tbl = pd.read_csv(DATA / "cir_longrun.csv")
    gas     = pd.read_csv(DATA / "gas_costs.csv")
    welfare = pd.read_csv(DATA / "welfare.csv")
    sofr    = pd.read_csv(DATA / "sofr_annual.csv")
    return panel, cir_tbl, gas, welfare, sofr


# ═══════════════════════════════════════════════════════════════════════════
# TABLES
# ═══════════════════════════════════════════════════════════════════════════

def table1_descriptive(panel):
    agg = (panel.groupby("country")
                .agg(
                    obs       = ("kappa_hat",      "count"),
                    khat_mean = ("kappa_hat",      "mean"),
                    khat_std  = ("kappa_hat",      "std"),
                    s_obs     = ("s_obs_bps",      "mean"),
                    s_star    = ("s_star_bps",     "mean"),
                    s_conv    = ("s_conv_bps",      "mean"),
                    riba_prem = ("riba_premium_bps","mean"),
                )
                .reset_index())

    order = ["UAE","Kuwait","Qatar","Saudi Arabia","Malaysia","Indonesia","Bahrain"]
    agg = agg.set_index("country").loc[order].reset_index()

    lines = [
        r"% Table 1: Descriptive Statistics",
        r"% Auto-generated by icds_pipeline.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Descriptive Statistics: iCDS Spread Decomposition, 2012--2025.}",
        r"\label{tab:desc}",
        r"\small",
        r"\begin{tabular}{lrrrrrrr}",
        r"\toprule",
        r"Country & $T$ & $\bar{\hat{\kappa}}$ (\%) & $\sigma_{\hat{\kappa}}$ & "
        r"$\bar{s}_{\text{obs}}$ (bps) & $s^*_{\iota=0}$ (bps) & "
        r"$s_{\text{conv}}$ (bps) & Riba prem. (bps) \\",
        r"\midrule",
    ]
    for _, r in agg.iterrows():
        lines.append(
            f"{r.country} & {int(r.obs)} & {r.khat_mean*100:.3f} & {r.khat_std*100:.3f} & "
            f"{r.s_obs:.1f} & {r.s_star:.1f} & {r.s_conv:.1f} & {r.riba_prem:.1f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}",
              r"\begin{minipage}{\textwidth}",
              r"\smallskip\footnotesize",
              r"\textit{Notes}: $T$ = monthly observations (168 per country)."
              r" $s^*_{\iota=0}=\hat{\kappa}(1-\delta)\times10{,}000$."
              r" $s_\text{conv}=\hat{\kappa}(1{-}\delta)\cdot\iota/(\hat{\kappa}+\iota)$"
              r" where $\iota$ is the annual SOFR. Riba premium $=s^*_{\iota=0}-s_\text{conv}$."
              r" $\delta=0.60$ throughout.",
              r"\end{minipage}",
              r"\end{table}", ""]
    (TABS / "table1_desc.tex").write_text("\n".join(lines))
    print("  table1_desc.tex")


def table2_pricing_comparison(panel, sofr):
    # Annual cross-country means
    panel["year"] = pd.to_datetime(panel["obs_date"]).dt.year
    ann = (panel.groupby(["country","year"])
                .agg(s_star=("s_star_bps","mean"),
                     s_conv=("s_conv_bps","mean"),
                     s_cds =("cds_spread_bps","mean"))
                .reset_index())
    # Pivot to wide for selected years
    years = [2015, 2018, 2020, 2022, 2023, 2025]
    order = ["UAE","Kuwait","Qatar","Saudi Arabia","Malaysia","Indonesia","Bahrain"]
    lines = [
        r"% Table 2: Annual Pricing Comparison",
        r"% Auto-generated by icds_pipeline.py",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Annual iCDS vs.\ Conventional CDS Spreads (basis points).}",
        r"\label{tab:pricing}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l" + "rrr" * len(years) + "}",
        r"\toprule",
        r"\multicolumn{1}{l}{} & " +
        " & ".join([r"\multicolumn{3}{c}{" + str(y) + "}" for y in years]) + r" \\",
        r"\cmidrule(lr){2-4}" + "".join([
            r"\cmidrule(lr){" + str(3*i+2) + "-" + str(3*i+4) + "}"
            for i in range(1, len(years))
        ]),
        "Country & " + " & ".join([r"$s^*$ & $s_\text{c}$ & $s_\text{obs}$"] * len(years)) + r" \\",
        r"\midrule",
    ]
    for country in order:
        row_parts = [country]
        sub = ann[ann["country"] == country]
        for y in years:
            yr = sub[sub["year"] == y]
            if len(yr):
                r = yr.iloc[0]
                s_star = f"{r.s_star:.0f}" if not np.isnan(r.s_star) else "—"
                s_conv = f"{r.s_conv:.0f}" if not np.isnan(r.s_conv) else "—"
                s_cds  = f"{r.s_cds:.0f}"  if not np.isnan(r.s_cds) else "—"
            else:
                s_star = s_conv = s_cds = "—"
            row_parts += [s_star, s_conv, s_cds]
        lines.append(" & ".join(row_parts) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{\textwidth}",
        r"\smallskip\footnotesize",
        r"\textit{Notes}: $s^*=\hat{\kappa}(1{-}\delta)\times10{,}000$ (iCDS at $\iota=0$)."
        r" $s_\text{c}=\hat{\kappa}(1{-}\delta)\cdot\iota/(\hat{\kappa}+\iota)\times10{,}000$"
        r" (AHJ formula at $\iota=$SOFR). $s_\text{obs}$ = Damodaran (2026) sovereign"
        r" CDS spread. All in basis points. $\delta=0.60$.",
        r"\end{minipage}",
        r"\end{table}", "",
    ]
    (TABS / "table2_pricing.tex").write_text("\n".join(lines))
    print("  table2_pricing.tex")


def table3_longrun(cir_tbl):
    order = ["UAE","Kuwait","Qatar","Saudi Arabia","Malaysia","Indonesia","Bahrain"]
    cir_tbl = cir_tbl.set_index("country").loc[order].reset_index()

    lines = [
        r"% Table 3: Long-run pricing vs 2025 CDS",
        r"% Auto-generated by icds_pipeline.py",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Long-Run iCDS Pricing vs.\ January 2025 Damodaran CDS Spread.}",
        r"\label{tab:longrun}",
        r"\small",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Country & $\hat{\bar{\kappa}}$ (\%) & "
        r"$s^*_\text{LR}$ & $s_\text{conv,LR}$ & $s_\text{CDS,2025}$ & $s^*-s_\text{CDS}$ \\",
        r" & & \multicolumn{4}{c}{(basis points)} \\",
        r"\midrule",
    ]
    for _, r in cir_tbl.iterrows():
        diff = f"{r.s_star_lr - r.cds_2025:+.1f}" if not np.isnan(r.cds_2025) else "—"
        lines.append(
            f"{r.country} & {r.kbar_pct:.3f} & {r.s_star_lr:.1f} & "
            f"{r.s_conv_lr:.1f} & {r.cds_2025:.0f} & {diff} \\\\"
        )
    mean_diff = (cir_tbl["s_star_lr"] - cir_tbl["cds_2025"]).mean()
    lines += [
        r"\midrule",
        f"Mean & & & & & {mean_diff:+.1f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{\textwidth}",
        r"\smallskip\footnotesize",
        r"\textit{Notes}: $\hat{\bar{\kappa}}$ = CIR long-run mean from Table~6 of"
        r" Ahmed et al.\ (2026a). $s^*_\text{LR}=\hat{\bar{\kappa}}(1{-}\delta)\times10{,}000$."
        r" $s_{\text{conv,LR}}$ uses $\iota=\text{SOFR}_{2025}=5.34\%$."
        r" $s_\text{CDS,2025}$ from Damodaran~(2026)."
        r" Positive $s^*-s_\text{CDS}$ indicates the long-run iCDS price exceeds"
        r" current market spread (mean-reversion premium). $\delta=0.60$.",
        r"\end{minipage}",
        r"\end{table}", "",
    ]
    (TABS / "table3_longrun.tex").write_text("\n".join(lines))
    print("  table3_longrun.tex")


def table4_gas(gas_tbl):
    ETH_USD = 2800.0
    eth_mainnet = {
        "openProtection":     0.94,
        "acceptProtection":   0.63,
        "payPremium":         0.43,
        "triggerCreditEvent": 0.36,
        "settle":             0.50,
        "expire":             0.39,
        "Full lifecycle (1yr, 3 premiums + settlement)": 3.72,
    }
    lines = [
        r"% Table 4: Gas Cost Benchmarks",
        r"% Auto-generated by icds_pipeline.py",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Gas Cost Benchmarks: iCDS Lifecycle on Arbitrum One vs.\ Ethereum Mainnet.}",
        r"\label{tab:gas}",
        r"\small",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Function & Gas units & Arb.\ (\$) & ETH main.\ (\$) & Saving \\",
        r"\midrule",
    ]
    for _, r in gas_tbl.iterrows():
        step = r["step"]
        eth_cost = eth_mainnet.get(step, 0.0)
        saving   = (1 - r.usd_cost / eth_cost) * 100 if eth_cost > 0 else 0.0
        label    = step.replace("Full lifecycle (1yr, 3 premiums + settlement)", r"Full lifecycle$^\dagger$")
        lines.append(
            f"\\texttt{{{label}}} & {r.gas_units:,} & \\${r.usd_cost:.4f} & "
            f"\\${eth_cost:.2f} & {saving:.0f}\\% \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{\textwidth}",
        r"\smallskip\footnotesize",
        r"Arbitrum One: gas price $0.1$\,gwei, ETH/USD $=\$2{,}800$."
        r" Ethereum mainnet: gas price $20$\,gwei (median 2025)."
        r" $^\dagger$Full lifecycle $=$ open $+$ accept $+$ 3$\times$payPremium"
        r" $+$ triggerCreditEvent $+$ settle.",
        r"\end{minipage}",
        r"\end{table}", "",
    ]
    (TABS / "table4_gas.tex").write_text("\n".join(lines))
    print("  table4_gas.tex")


def table5_welfare(welfare):
    # Compute certainty-equivalent wealth (CEW)
    W0 = 10_000_000.0

    def cew(eu, gamma):
        """Inverse CRRA: CEW = (EU × (1-γ))^(1/(1-γ))"""
        if gamma == 1:
            return np.exp(eu)
        return (eu * (1 - gamma)) ** (1 / (1 - gamma))

    lines = [
        r"% Table 5: Welfare Analysis",
        r"% Auto-generated by icds_pipeline.py",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Welfare Analysis: Certainty-Equivalent Wealth for Saudi Arabia 5yr Sukuk.}",
        r"\label{tab:welfare}",
        r"\small",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"$\gamma$ & Premium (iCDS) & Premium (CDS) & CEW: Unhedged & CEW: iCDS & CEW: Conv.\ CDS \\",
        r"\midrule",
    ]
    for _, r in welfare.iterrows():
        gamma = int(r.gamma)
        # Compute expected utilities for CEW back-conversion
        # Unhedged
        kappa_sa = 0.02409; T = 5
        p_def = 1 - np.exp(-kappa_sa * T)
        W_nh_ok  = W0
        W_nh_def = W0 * (1 - LGD)
        W_icds   = W0 - r.prem_icds_usd
        W_cds    = W0 - r.prem_cds_usd

        def eu(w_ok, w_def, g):
            def u(w):
                if g == 1: return np.log(max(w,1))
                return (max(w,1)**(1-g))/(1-g)
            return (1-p_def)*u(w_ok) + p_def*u(w_def)

        eu_nh   = eu(W_nh_ok, W_nh_def, gamma)
        eu_icds = eu(W_icds,  W_icds,   gamma)
        eu_cds  = eu(W_cds,   W_cds,    gamma)

        cew_nh   = cew(eu_nh,   gamma)
        cew_icds = cew(eu_icds, gamma)
        cew_cds  = cew(eu_cds,  gamma)

        lines.append(
            f"{gamma} & \\${r.prem_icds_usd:,.0f} & \\${r.prem_cds_usd:,.0f} & "
            f"\\${cew_nh:,.0f} & \\${cew_icds:,.0f} & \\${cew_cds:,.0f} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{\textwidth}",
        r"\smallskip\footnotesize",
        r"\textit{Notes}: CRRA utility $u(W)=W^{1-\gamma}/(1-\gamma)$."
        r" Certainty-equivalent wealth (CEW) is the riskless wealth that yields the same"
        r" expected utility as the risky strategy."
        r" Reference entity: Saudi Arabia sovereign; notional $W_0=\$10{,}000{,}000$;"
        r" $T=5$ years; $\kappa=\hat{\bar{\kappa}}_\text{SA}=2.409\%$; $\delta=0.60$;"
        r" $\iota_\text{CDS}=\text{SOFR}_{2025}=5.34\%$."
        r" iCDS premium $=\hat{\kappa}(1{-}\delta)\cdot W_0\cdot T$;"
        r" CDS premium uses AHJ formula at $\iota=\text{SOFR}$.",
        r"\end{minipage}",
        r"\end{table}", "",
    ]
    (TABS / "table5_welfare.tex").write_text("\n".join(lines))
    print("  table5_welfare.tex")


def table6_jurisdictions():
    rows = [
        ("UAE / VARA",      "VARA Virtual Asset Reg.\ 2023", "Permissible",
         "Virtual asset derivative; seller must be licensed VASP; KYC/AML required"),
        ("Malaysia / BNM",  "IFSA 2013 + SC Guidelines",     "Permissible",
         "AAOIFI-compliant structure acceptable; BNM requires Shariah advisory board"),
        ("Singapore / MAS", "CMS Act + SF Act",              "Conditional",
         "OTC derivative: requires CMS licence; EMIR-style trade reporting likely"),
        ("UK / FCA",        "UK MAR + CMAR",                 "Conditional",
         "Treated as OTC swap; EMIR UK reporting; no Islamic finance carve-out"),
        ("US / CFTC",       "CEA + Dodd-Frank",              "Uncertain",
         "Likely classified as swap; SEF registration or bilateral ISDA/IIFM docs needed"),
        ("Bahrain / CBB",   "CBB Rulebook Vol.\ 2",          "Permissible",
         "Gulf-friendly pilot jurisdiction; CBB Module CM covers credit derivatives"),
    ]
    lines = [
        r"% Table 6: Jurisdictional Analysis",
        r"% Hand-coded from primary regulatory sources",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Jurisdictional Analysis: On-Chain iCDS Regulatory Status.}",
        r"\label{tab:juris}",
        r"\small",
        r"\begin{tabular}{llll}",
        r"\toprule",
        r"Jurisdiction & Primary Framework & Status & Key Requirement \\",
        r"\midrule",
    ]
    for jur, fw, status, note in rows:
        st = r"\textcolor{green!50!black}{\textbf{" + status + r"}}" if status == "Permissible" \
             else (r"\textcolor{orange!80!black}{\textit{" + status + r"}}" if status == "Conditional"
                   else r"\textcolor{red!70!black}{" + status + r"}")
        lines.append(f"{jur} & {fw} & {st} & \\small {note} \\\\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\begin{minipage}{\textwidth}",
        r"\smallskip\footnotesize",
        r"\textit{Sources}: VARA Virtual Asset and Related Activities Regulation (2023);"
        r" BNM Islamic Financial Services Act 2013; MAS Capital Markets Services Act;"
        r" FCA UK CMAR; CFTC Commodity Exchange Act \S{}2(h); CBB Rulebook Vol.\ 2"
        r" (Capital Markets, Module CM). Status reflects the authors' legal assessment;"
        r" independent regulatory counsel advised before commercial launch.",
        r"\end{minipage}",
        r"\end{table}", "",
    ]
    (TABS / "table6_juris.tex").write_text("\n".join(lines))
    print("  table6_juris.tex")


# ═══════════════════════════════════════════════════════════════════════════
# FIGURES
# ═══════════════════════════════════════════════════════════════════════════

COUNTRY_ORDER = ["UAE","Kuwait","Qatar","Saudi Arabia","Malaysia","Indonesia","Bahrain"]


def fig1_timeseries(panel):
    fig, axes = plt.subplots(3, 3, figsize=(13, 9))
    axes_flat = axes.flatten()

    for idx, country in enumerate(COUNTRY_ORDER):
        ax  = axes_flat[idx]
        sub = panel[panel["country"] == country].sort_values("obs_date")
        x   = pd.to_datetime(sub["obs_date"])

        ax.plot(x, sub["s_star_bps"],  "-",  color="black",      lw=1.4,
                label=r"$s^*_{\iota=0}$")
        ax.plot(x, sub["s_conv_bps"],  "--", color="steelblue",   lw=1.2,
                label=r"$s_\text{conv}(\iota=\text{SOFR})$")
        # Annual CDS dots
        sub_cds = sub.dropna(subset=["cds_spread_bps"]).drop_duplicates("year")
        ax.scatter(pd.to_datetime(sub_cds["obs_date"]),
                   sub_cds["cds_spread_bps"],
                   s=20, color="crimson", zorder=5,
                   label="Damodaran CDS")

        ax.set_title(country, fontsize=8.5)
        ax.xaxis.set_major_locator(mdates.YearLocator(3))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
        ax.tick_params(labelsize=7)
        ax.set_ylabel("bps", fontsize=7)

    for j in range(7, 9):
        axes_flat[j].set_visible(False)

    handles, labels = axes_flat[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower right",
               bbox_to_anchor=(0.97, 0.06), fontsize=8, framealpha=0.9)
    fig.suptitle(r"iCDS Spread Decomposition: $s^*_{\iota=0}$ vs $s_\text{conv}(\iota=\text{SOFR})$"
                 "\nvs Damodaran Sovereign CDS (2012–2025)", fontsize=10.5)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    path = FIGS / "fig1_spread_timeseries.pdf"
    plt.savefig(path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  {path.name}")


def fig2_scatter(panel):
    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    colors = plt.cm.tab10(np.linspace(0, 1, 7))
    for i, country in enumerate(COUNTRY_ORDER):
        sub = panel[(panel["country"] == country)
                    & panel["cds_spread_bps"].notna()
                    & panel["s_conv_bps"].notna()]
        ax.scatter(sub["cds_spread_bps"], sub["s_conv_bps"],
                   s=15, alpha=0.55, color=colors[i], label=country)

    # 45-degree line
    lim = max(panel["cds_spread_bps"].max(), panel["s_conv_bps"].max()) * 1.05
    ax.plot([0, lim], [0, lim], "--", color="grey", lw=1, label="45° line")

    # OLS fit
    mask = panel["cds_spread_bps"].notna() & panel["s_conv_bps"].notna()
    x = panel.loc[mask, "cds_spread_bps"].values
    y = panel.loc[mask, "s_conv_bps"].values
    m, b = np.polyfit(x, y, 1)
    xr = np.linspace(0, lim, 200)
    ax.plot(xr, m*xr+b, "-", color="black", lw=1.2,
            label=f"OLS: slope={m:.3f}, intercept={b:.1f}")

    ss_res = np.sum((y - (m*x+b))**2)
    ss_tot = np.sum((y - y.mean())**2)
    r2 = 1 - ss_res/ss_tot

    ax.set_xlabel("Damodaran CDS spread (bps)", fontsize=10)
    ax.set_ylabel(r"$s_\text{conv}(\iota=\text{SOFR})$ (bps)", fontsize=10)
    ax.set_title(f"AHJ Formula vs.\ Damodaran CDS  ($R^2={r2:.3f}$, $N={mask.sum():,}$)",
                 fontsize=10)
    ax.legend(fontsize=7.5, ncol=2)
    ax.set_xlim(0, lim); ax.set_ylim(0, lim)

    path = FIGS / "fig2_scatter.pdf"
    plt.tight_layout()
    plt.savefig(path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  {path.name}")


def fig3_riba_premium(panel):
    panel["year"] = pd.to_datetime(panel["obs_date"]).dt.year
    ann = (panel.groupby(["country","year"])["riba_premium_bps"]
               .mean().reset_index())

    fig, ax = plt.subplots(figsize=(10, 5))
    years = sorted(ann["year"].unique())
    x = np.arange(len(years))
    width = 0.11
    colors = plt.cm.tab10(np.linspace(0, 1, 7))
    for i, country in enumerate(COUNTRY_ORDER):
        sub = ann[ann["country"] == country].set_index("year")
        vals = [sub.loc[y, "riba_premium_bps"] if y in sub.index else 0.0 for y in years]
        ax.bar(x + i*width, vals, width, label=country, color=colors[i], alpha=0.85)

    ax.set_xticks(x + 3*width)
    ax.set_xticklabels(years, rotation=45, ha="right", fontsize=8)
    ax.set_ylabel("Riba premium (bps)", fontsize=10)
    ax.set_title(r"Annual Riba Premium $= s^*_{\iota=0} - s_\text{conv}(\iota=\text{SOFR})$"
                 "\n(basis points removed by setting $\\iota=0$)", fontsize=10)
    ax.legend(fontsize=7.5, ncol=4, loc="upper right")

    path = FIGS / "fig3_riba_premium.pdf"
    plt.tight_layout()
    plt.savefig(path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  {path.name}")


def fig4_gas(gas_tbl):
    ETH_COSTS = {
        "openProtection": 0.94, "acceptProtection": 0.63,
        "payPremium": 0.43, "triggerCreditEvent": 0.36,
        "settle": 0.50, "expire": 0.39,
    }
    sub = gas_tbl[gas_tbl["step"] != "Full lifecycle (1yr, 3 premiums + settlement)"].copy()

    labels = sub["step"].values
    arb    = sub["usd_cost"].values
    eth    = [ETH_COSTS.get(s, 0) for s in labels]

    y = np.arange(len(labels))
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.barh(y - 0.18, eth, 0.35, label="Ethereum mainnet (20 gwei)", color="tomato",   alpha=0.85)
    ax.barh(y + 0.18, arb, 0.35, label="Arbitrum One (0.1 gwei)",    color="steelblue", alpha=0.85)
    ax.set_yticks(y)
    ax.set_yticklabels([s.replace("Protection","Prot.") for s in labels], fontsize=9)
    ax.set_xlabel("Transaction cost (USD)", fontsize=10)
    ax.set_title("iCDS Gas Costs: Arbitrum One vs.\ Ethereum Mainnet", fontsize=10)
    ax.legend(fontsize=9)
    ax.set_xscale("log")
    for xi, yi in zip(eth, y - 0.18):
        ax.text(xi*1.05, yi, f"${xi:.2f}", va="center", fontsize=7, color="darkred")
    for xi, yi in zip(arb, y + 0.18):
        ax.text(xi*1.05, yi, f"${xi:.4f}", va="center", fontsize=7, color="navy")

    path = FIGS / "fig4_gas.pdf"
    plt.tight_layout()
    plt.savefig(path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  {path.name}")


def fig5_welfare(welfare):
    W0 = 10_000_000.0
    kappa_sa = 0.02409; T = 5
    p_def = 1 - np.exp(-kappa_sa * T)

    fig, axes = plt.subplots(1, 3, figsize=(12, 4.5), sharey=False)
    gammas = [2, 5, 10]
    strategy_labels = ["Unhedged", "iCDS ($\\iota=0$)", "Conv.\ CDS"]

    for j, gamma in enumerate(gammas):
        ax = axes[j]
        r  = welfare[welfare["gamma"] == gamma].iloc[0]

        W_nh_ok  = W0
        W_nh_def = W0 * (1 - LGD)
        W_icds   = W0 - r.prem_icds_usd
        W_cds    = W0 - r.prem_cds_usd

        def eu(w_ok, w_def, g):
            def u(w):
                if g == 1: return np.log(max(w,1))
                return (max(w,1)**(1-g))/(1-g)
            return (1-p_def)*u(w_ok) + p_def*u(w_def)

        def cew(eu_v, g):
            if g == 1: return np.exp(eu_v)
            return (eu_v * (1-g)) ** (1/(1-g))

        eu_nh   = eu(W_nh_ok, W_nh_def, gamma)
        eu_icds = eu(W_icds,  W_icds,   gamma)
        eu_cds  = eu(W_cds,   W_cds,    gamma)

        cews = [cew(eu_nh, gamma)/1e6, cew(eu_icds, gamma)/1e6, cew(eu_cds, gamma)/1e6]
        colors = ["tomato", "steelblue", "gold"]
        bars = ax.bar(strategy_labels, cews, color=colors, alpha=0.85, edgecolor="black", lw=0.5)

        for bar, v in zip(bars, cews):
            ax.text(bar.get_x() + bar.get_width()/2, v + 0.01,
                    f"${v:.2f}M", ha="center", va="bottom", fontsize=8)

        ax.set_title(f"$\\gamma = {gamma}$", fontsize=10)
        ax.set_ylabel("Certainty-equivalent wealth ($M)" if j == 0 else "")
        ax.tick_params(axis="x", labelsize=8)
        ax.set_ylim(min(cews)*0.97, max(cews)*1.03)

    fig.suptitle("Certainty-Equivalent Wealth by Hedging Strategy\n"
                 "(Saudi Arabia sovereign, $W_0=\\$10$M, 5-year tenor)", fontsize=10.5)
    plt.tight_layout()
    path = FIGS / "fig5_welfare.pdf"
    plt.savefig(path, dpi=160, bbox_inches="tight")
    plt.close()
    print(f"  {path.name}")


# ═══════════════════════════════════════════════════════════════════════════
# SUMMARY STATS for paper text
# ═══════════════════════════════════════════════════════════════════════════

def print_summary(panel, cir_tbl, gas_tbl):
    print("\n── Key numbers for paper body ──────────────────────────────")
    mask = panel["cds_spread_bps"].notna() & panel["s_conv_bps"].notna()
    x  = panel.loc[mask, "cds_spread_bps"].values
    y  = panel.loc[mask, "s_conv_bps"].values
    m, b = np.polyfit(x, y, 1)
    ss_res = np.sum((y-(m*x+b))**2)
    r2 = 1 - ss_res/np.sum((y-y.mean())**2)
    rmse = np.sqrt(np.mean((y-x)**2))
    print(f"  Scatter R² (s_conv vs CDS): {r2:.4f}")
    print(f"  RMSE s_conv vs CDS: {rmse:.2f} bps")
    print(f"  OLS slope: {m:.4f}, intercept: {b:.2f}")
    print(f"  N obs in scatter: {mask.sum():,}")

    mean_riba = panel["riba_premium_bps"].mean()
    print(f"  Mean riba premium (all): {mean_riba:.2f} bps")
    inv_grade = ["UAE","Kuwait","Qatar","Saudi Arabia","Malaysia"]
    inv_panel = panel[panel["country"].isin(inv_grade)]
    print(f"  Mean riba premium (inv. grade): {inv_panel['riba_premium_bps'].mean():.2f} bps")

    full_lc = gas_tbl[gas_tbl["step"].str.startswith("Full")].iloc[0]
    print(f"  Full lifecycle gas: {full_lc.gas_units:,} units  ~${full_lc.usd_cost:.4f}")

    print(f"  Mean %above CDS (long-run): {cir_tbl['pct_above_cds'].mean():.1f}%")

    # Error between s_conv and Damodaran for inv-grade GCC
    gcc_inv = ["UAE","Kuwait","Qatar","Saudi Arabia"]
    sub = cir_tbl[cir_tbl["country"].isin(gcc_inv)]
    errs = (sub["s_conv_lr"] - sub["cds_2025"]) / sub["cds_2025"] * 100
    print(f"  GCC inv-grade s_conv vs CDS 2025 errors: {errs.values}")
    print(f"    Mean abs error: {errs.abs().mean():.1f}%")


# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════

def main():
    panel, cir_tbl, gas_tbl, welfare, sofr = load()

    # patch year column
    panel["year"] = pd.to_datetime(panel["obs_date"]).dt.year

    print("Generating tables...")
    table1_descriptive(panel)
    table2_pricing_comparison(panel, sofr)
    table3_longrun(cir_tbl)
    table4_gas(gas_tbl)
    table5_welfare(welfare)
    table6_jurisdictions()

    print("Generating figures...")
    fig1_timeseries(panel)
    fig2_scatter(panel)
    fig3_riba_premium(panel)
    fig4_gas(gas_tbl)
    fig5_welfare(welfare)

    print_summary(panel, cir_tbl, gas_tbl)
    print("\nDone.")


if __name__ == "__main__":
    main()
